"""empty message

Revision ID: ca2290d0e80e
Revises: 478f3d70775b
Create Date: 2020-06-22 22:27:26.272113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2290d0e80e'
down_revision = '478f3d70775b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('num_rows', sa.Integer(), nullable=True))
    op.add_column('dataset', sa.Column('version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'version')
    op.drop_column('dataset', 'num_rows')
    # ### end Alembic commands ###
