"""empty message
Revision ID: 17c3ca14e0d7
Revises: ca2290d0e80e
Create Date: 2020-06-22 22:28:04.561377
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17c3ca14e0d7"
down_revision = "ca2290d0e80e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dataset_name", table_name="dataset")
    op.create_index(op.f("ix_dataset_name"), "dataset", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dataset_name"), table_name="dataset")
    op.create_index("ix_dataset_name", "dataset", ["name"], unique=True)
    # ### end Alembic commands ###
