"""empty message
Revision ID: 478f3d70775b
Revises: 6802cdc1818c
Create Date: 2020-06-22 22:23:56.776416
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "478f3d70775b"
down_revision = "6802cdc1818c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("type", sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "type")
    # ### end Alembic commands ###
