"""empty message
Revision ID: 6802cdc1818c
Revises: 6d1ae80450d9
Create Date: 2020-06-22 21:22:00.678936
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6802cdc1818c"
down_revision = "6d1ae80450d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("header", sa.JSON(), nullable=True))
    op.drop_column("dataset", "first_row")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "dataset",
        sa.Column(
            "first_row", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("dataset", "header")
    # ### end Alembic commands ###
