"""empty message
Revision ID: 6d1ae80450d9
Revises: 
Create Date: 2020-06-18 22:25:39.433197
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6d1ae80450d9"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("first_row", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dataset_name"), "dataset", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dataset_name"), table_name="dataset")
    op.drop_table("dataset")
    # ### end Alembic commands ###
